### PR TITLE
Create jekyll-docker.yml

### PR DESCRIPTION
**Pull request by viktor2102**

### CODE REVIEW

**Comment by nanis94** [comment]
#57 viktor2102:main

**Comment by nanis94** [comment]
viktor2102:main

**Review by nanis94 — COMMENTED** [review]
viktor2102:main

**Review by nanis94 — COMMENTED** [review]
.github/iş akışları/jekyll-docker.yml main

**Comment by Asp3569** [comment]
R

**Review by sammyfilly — COMMENTED** [review]
Approve

**Pull request closed without merging**
