### PR TITLE
add link to official IP ranges documentation

### PR DESCRIPTION
**Pull request by sebastian-lerner**
IP ranges supports this functionality officially.  it is in open preview for paid customers

### CODE REVIEW

**Comment by sebastian-lerner** [comment]
@perezjc this is the PR, thank you!

**Review by perezjc — APPROVED** [review]

**Review by perezjc — APPROVED** [review]
Approved

**Comment by sebastian-lerner** [comment]
@rosieyohannan do you have write access to merge this?

**Comment by rosieyohannan** [comment]
> @rosieyohannan do you have write access to merge this?

no I don't sorry!

**Comment by sebastian-lerner** [comment]
@perezjc i don't have access to push these changes, do you by any chance?

**Comment by perezjc** [comment]
@sebastian-lerner it doesn't look like it, let me find out who can

**Review by ganezasan — APPROVED** [review]
LGTM

**Pull request merged**
